service: cloudwatch-logs

plugins:
 - serverless-pseudo-parameters
 - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  memorySize: 128
  stage: dev
  versionFunctions: false

functions:
  worker:
    handler: bin/worker
    description: Sends CloudWatch logs to Logz.io
    environment:
      logstash_host: listener.logz.io
      logstash_port: 5015
      token: palOPqZOzEnDKhrVYZvgEmZzJqWRaVdp

resources:
  Resources:
    LambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName:
          Fn::Join:
            - ""
            - - "Ref" : "ShipDashlogsDashtoDashlogzioLambdaFunction"
        Principal: logs.#{AWS::Region}.amazonaws.com
