service: cloudwatch-logs

plugins:
 - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  memorySize: 128
  stage: dev
  versionFunctions: false

functions:
  worker:
    handler: bin/worker
    description: Sends CloudWatch logs to Logz.io
    environment:
      HOST: listener.logz.io
      PORT: 5015
      TOKEN: palOPqZOzEnDKhrVYZvgEmZzJqWRaVdp

resources:
  Resources:
    LambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName:
          Fn::Join:
            - ""
            - - "Ref" : "ShipDashlogsDashtoDashlogzioLambdaFunction"
        Principal: logs.#{AWS::Region}.amazonaws.com
