service: cloudwatch-logs

plugins:
  - serverless-plugin-log-retention

custom:
  logRetentionInDays: 7

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  memorySize: 128
  stage: dev
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

functions:
  worker:
    handler: bin/worker
    description: Sends CloudWatch logs to Logz.io
    environment:
      HOST: listener.logz.io
      PORT: 8071
      TOKEN: palOPqZOzEnDKhrVYZvgEmZzJqWRaVdp
